#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

git update-server-info
git archive master | tar -x -C /var www
git archive master | tar -x --strip-components=1 -C /var/www orthoeman/orthoeman.xsd
git archive master | tar -x --exclude orthoeman/AuthoringTool -C /usr/share/moodle/mod orthoeman
mkdir -p /usr/share/moodle/mod/orthoeman/AuthoringTool
git archive master | tar -x --strip-components=3 -C /usr/share/moodle/mod/orthoeman/AuthoringTool orthoeman/AuthoringTool/war
#git archive master | tar -x -C /usr/share/moodle/mod/orthoeman Display
